CC=gcc
CFLAGS=-g -std=c99 -Wall
#LDFLAGS=-lm

test3:
	./part3 #no parameters
	./part3 "hello"
	./part3 "how are you doing" "cat" "melody"
	./part3 "biggest" "parameter" "at" "end" "very very very big parameter"
	./part3 "answer" "somewhere" "in" "the" "middle"
	./part3 "two" "strings" "the" "same" "length" "ha ha !"

test4:
	./part4 #no parameters
	./part4 -c
	./part4 -a 256
	./part4 -c -274.67
	./part4 -f -10
	./part4 -c 35
	./part4 -c -12
	./part4 -f 804
	./part4 -f 45

test5:
	./part5 #no parameters
	./part5 hello There
	./part5 input_empty
	./part5 input1
	./part5 input2
